# More info about AWS Serverless Application Model (SAM):
# https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for local debugging Lambda functions.

Globals:
  Function:
    Runtime: nodejs18.x
    Handler: index.handler
    Timeout: 10000
    MemorySize: 1024
    Environment:
      Variables:
        NODE_ENV: development
        AUTH_JWT_SECRET: 7b6s4BlGn5eswpLBQueL2coaDrf250vL2IpDoQCq0DtmsEPZBQlssksVfM1YB2l
        RDS_DB_HOST: tikitup-test.ceyeogpl2bhv.eu-west-1.rds.amazonaws.com
        RDS_DB_NAME: tikitup
        RDS_DB_USER: admin
        RDS_DB_PASS: iPEqnOKbpQdUOKXMEiKP
        SQS_QUEUE_NAME: tikitup-test.fifo
        DS_MERCHANT_SECRETKEYS: sq7HjrUOBfKmC576ILgskD5srU870gJ7
        PAYPAL_MODE: sandbox
        PAYPAL_CLIENT_ID: Adm-VwOdiaOG4ostRy8E2hKT37UPC4W1OcjMOKE7G42mwCFez9rqv53208KJG05CaJuayD3eaEFeqWAI
        PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
        PAYPAL_CLIENT_ID_FESTAMATCH: ${PAYPAL_CLIENT_ID_FESTAMATCH}
        PAYPAL_CLIENT_SECRET_FESTAMATCH: ${PAYPAL_CLIENT_SECRET_FESTAMATCH}
        STRIPE_SECRET: ${STRIPE_SECRET}
        STRIPE_ENDPOINT_SECRET: ${STRIPE_ENDPOINT_SECRET}

Resources:
  HousingManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./packages/housing-management/dist
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /v1/housing
            Method: post
        FindAllHousing:
          Type: Api
          Properties:
            Path: /v1/housing
            Method: get
        FindHousingById:
          Type: Api
          Properties:
            Path: /v1/housing/{id}
            Method: get
        UpdateHousing:
          Type: Api
          Properties:
            Path: /v1/housing/{id}
            Method: put
        DeleteHousing:
          Type: Api
          Properties:
            Path: /v1/housing/{id}
            Method: delete
        FindAllOwners:
          Type: Api
          Properties:
            Path: /v1/housing/owners
            Method: get
        FindOwnerById:
          Type: Api
          Properties:
            Path: /v1/housing/owners/{id}
            Method: get
        UpdateOwner:
          Type: Api
          Properties:
            Path: /v1/housing/owners/{id}
            Method: put
        FindHousingDomainEvents:
          Type: Api
          Properties:
            Path: /v1/housing/events
            Method: get
